all: vet static build test

.PHONY: vet
vet:
	@echo Running go vet...
	@go vet ./...

.PHONY: static
static:
	@echo Running staticcheck...
	@staticcheck ./...

.PHONY: build
build:
	@echo Building...
	@go build -o bin/ ./...

.PHONY: test
test:
	@echo Running tests...
	@go test ./...

.PHONY: cover
cover:
	@go test -count=1 -p=1 -coverprofile=coverage.out ./...
	@go tool cover -html=coverage.out